version: '3.7'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'oafishcaveman'
      POSTGRES_DB: 'inherits-demo'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d inherits-demo']
      interval: 10s
      timeout: 5s

volumes:
  postgres-data:
